define(['uiRouter'],function(){
	angular.module('shopcarModule',['ui.router'])
		.config(function($stateProvider,$urlRouterProvider){
			$stateProvider
				.state('shopcar',{
					url:'/shopcar',
					templateUrl:'component/shopcar/shopcar.html',
					css:'component/shopcar/shopcar.css',
					controller:'shopcarCtrl'
				});
		})
		.controller('shopcarCtrl',['$scope',function($scope){
			$scope.choose=true;
			$scope.goback=function(){
				window.history.go(-1);
			}
		}])
		
});
